GET http://localhost:5150/games

###
GET http://localhost:5150/games/1

###
POST http://localhost:5150/games
Content-Type: application/json

{
 "name": "Minecraft",
 "genre": "Kids and Family",
 "price": 19.99,
 "releaseDate": "2011-05-01"
}

###
PUT http://localhost:5150/games/1
Content-Type: application/json

{
    "name": "Street Fighter 2 turbo",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "2000-12-31"
}

###
DELETE http://localhost:5150/games/1